### ISSUE TITLE
Favicon Needs Updated

### ISSUE THREAD

**Issue by blanchardjeremy** [phaistonian/Asana-Plus#2]
Asana changed it favicon and logo a while ago to be 3 red dot in a triangle.

Is it possible to update the asana plus favicon to match?

I think you're attempting to do something regarding notifications using the favicon. I that the same thing that Asana is already doing now with a black dot (which represents new items in the inbox)?

![screen shot 2017-04-20 at 8 09 48 am](https://cloud.githubusercontent.com/assets/32290/25237904/c14ff3e2-25a0-11e7-9d2e-c0435ac71749.png)

Perhaps it would be best to just remove the favicon notification feature from Asana Plus and go back to the default favicon.

**Comment by phaistonian** [comment]
Should be done :)

(0.16.0)

**Comment by blanchardjeremy** [comment]
Thanks!
