### ISSUE TITLE
Extension conflicts with Upgrade/Purchase page

### ISSUE THREAD

**Issue by danrochman** [phaistonian/Asana-Plus#4]
Far from critical, but I happened to run into this today while upgrading (to a paid plan):
![image](https://cloud.githubusercontent.com/assets/208948/26748045/39ffc5d0-47af-11e7-9b20-d5d77f236de2.png)

I worked around it by disabling the extension temporarily, which is a simple and quick workaround.  And considering how often one would actually run into this, that's really enough.  But I thought it was worth mentioning - and I'm also curious as to how/whether the extension could be modified to avoid the error entirely.

Thanks for a great extension!!

**Comment by phaistonian** [comment]
zczxcz
